name: Optimize Static Files for Cloudflare Pages
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Replace Bunny Fonts with Google Fonts
        # Since Cloudflare seems to only support Google Fonts,
        # we need to replace the font provider in our HTML and CSS files,
        # so Cloudflare can properly cache and serve the fonts.
        env:
          OLD_FONT_DOMAIN: "fonts.bunny.net"
          NEW_FONT_DOMAIN: "fonts.googleapis.com"
        run: |
          find . -type f \( -name "*.html" -o -name "*.css" \) -exec perl -pi -e "s/$OLD_FONT_DOMAIN/$NEW_FONT_DOMAIN/g" {} +

      - name: Fix SEO Social Preview Images
        # Since social preview images are relative URLs,
        # we need to convert them to absolute URLs,
        # so they can be properly displayed when shared on social media platforms.
        env:
          MY_DOMAIN: "https://rhsu.cc/"
        run: |
          find . -type f -name "*.html" -exec perl -pi -e "s|property=\"og:image\" content=\"(?!http)([^\"]+)\"|property=\"og:image\" content=\"$MY_DOMAIN\1\"|g" {} +
          find . -type f -name "*.html" -exec perl -pi -e "s|(?:name\|property)=\"twitter:image\" content=\"(?!http)([^\"]+)\"|property=\"twitter:image\" content=\"${MY_DOMAIN}\1\"|g" {} +

      - name: Commit & Push Optimized Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: optimize static files [skip ci]"
          git push
